awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.1.Q >> admixture_k1.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.2.Q >> admixture_k2.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.3.Q >> admixture_k3.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.4.Q >> admixture_k4.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.5.Q >> admixture_k5.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.6.Q >> admixture_k6.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.7.Q >> admixture_k7.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.8.Q >> admixture_k8.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.9.Q >> admixture_k9.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.10.Q >> admixture_k10.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.11.Q >> admixture_k11.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.12.Q >> admixture_k12.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.13.Q >> admixture_k13.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.14.Q >> admixture_k14.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.15.Q >> admixture_k15.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.16.Q >> admixture_k16.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.17.Q >> admixture_k17.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.18.Q >> admixture_k18.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.19.Q >> admixture_k19.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.20.Q >> admixture_k20.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.21.Q >> admixture_k21.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.22.Q >> admixture_k22.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.23.Q >> admixture_k23.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.24.Q >> admixture_k24.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.25.Q >> admixture_k25.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.26.Q >> admixture_k26.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.27.Q >> admixture_k27.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.28.Q >> admixture_k28.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.29.Q >> admixture_k29.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.30.Q >> admixture_k30.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.31.Q >> admixture_k31.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.32.Q >> admixture_k32.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.33.Q >> admixture_k33.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.34.Q >> admixture_k34.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture11/cycas.maffiltered.4dtv.snp.35.Q >> admixture_k35.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.1.Q >> admixture_k1.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.2.Q >> admixture_k2.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.3.Q >> admixture_k3.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.4.Q >> admixture_k4.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.5.Q >> admixture_k5.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.6.Q >> admixture_k6.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.7.Q >> admixture_k7.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.8.Q >> admixture_k8.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.9.Q >> admixture_k9.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.10.Q >> admixture_k10.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.11.Q >> admixture_k11.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.12.Q >> admixture_k12.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.13.Q >> admixture_k13.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.14.Q >> admixture_k14.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.15.Q >> admixture_k15.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.16.Q >> admixture_k16.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.17.Q >> admixture_k17.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.18.Q >> admixture_k18.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.19.Q >> admixture_k19.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.20.Q >> admixture_k20.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.21.Q >> admixture_k21.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.22.Q >> admixture_k22.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.23.Q >> admixture_k23.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.24.Q >> admixture_k24.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.25.Q >> admixture_k25.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.26.Q >> admixture_k26.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.27.Q >> admixture_k27.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.28.Q >> admixture_k28.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.29.Q >> admixture_k29.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.30.Q >> admixture_k30.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.31.Q >> admixture_k31.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.32.Q >> admixture_k32.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.33.Q >> admixture_k33.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.34.Q >> admixture_k34.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture12/cycas.maffiltered.4dtv.snp.35.Q >> admixture_k35.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.1.Q >> admixture_k1.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.2.Q >> admixture_k2.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.3.Q >> admixture_k3.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.4.Q >> admixture_k4.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.5.Q >> admixture_k5.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.6.Q >> admixture_k6.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.7.Q >> admixture_k7.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.8.Q >> admixture_k8.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.9.Q >> admixture_k9.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.10.Q >> admixture_k10.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.11.Q >> admixture_k11.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.12.Q >> admixture_k12.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.13.Q >> admixture_k13.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.14.Q >> admixture_k14.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.15.Q >> admixture_k15.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.16.Q >> admixture_k16.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.17.Q >> admixture_k17.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.18.Q >> admixture_k18.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.19.Q >> admixture_k19.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.20.Q >> admixture_k20.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.21.Q >> admixture_k21.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.22.Q >> admixture_k22.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.23.Q >> admixture_k23.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.24.Q >> admixture_k24.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.25.Q >> admixture_k25.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.26.Q >> admixture_k26.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.27.Q >> admixture_k27.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.28.Q >> admixture_k28.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.29.Q >> admixture_k29.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.30.Q >> admixture_k30.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.31.Q >> admixture_k31.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.32.Q >> admixture_k32.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.33.Q >> admixture_k33.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.34.Q >> admixture_k34.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture13/cycas.maffiltered.4dtv.snp.35.Q >> admixture_k35.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.1.Q >> admixture_k1.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.2.Q >> admixture_k2.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.3.Q >> admixture_k3.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.4.Q >> admixture_k4.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.5.Q >> admixture_k5.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.6.Q >> admixture_k6.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.7.Q >> admixture_k7.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.8.Q >> admixture_k8.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.9.Q >> admixture_k9.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.10.Q >> admixture_k10.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.11.Q >> admixture_k11.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.12.Q >> admixture_k12.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.13.Q >> admixture_k13.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.14.Q >> admixture_k14.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.15.Q >> admixture_k15.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.16.Q >> admixture_k16.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.17.Q >> admixture_k17.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.18.Q >> admixture_k18.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.19.Q >> admixture_k19.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.20.Q >> admixture_k20.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.21.Q >> admixture_k21.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.22.Q >> admixture_k22.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.23.Q >> admixture_k23.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.24.Q >> admixture_k24.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.25.Q >> admixture_k25.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.26.Q >> admixture_k26.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.27.Q >> admixture_k27.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.28.Q >> admixture_k28.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.29.Q >> admixture_k29.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.30.Q >> admixture_k30.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.31.Q >> admixture_k31.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.32.Q >> admixture_k32.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.33.Q >> admixture_k33.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.34.Q >> admixture_k34.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture14/cycas.maffiltered.4dtv.snp.35.Q >> admixture_k35.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.1.Q >> admixture_k1.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.2.Q >> admixture_k2.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.3.Q >> admixture_k3.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.4.Q >> admixture_k4.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.5.Q >> admixture_k5.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.6.Q >> admixture_k6.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.7.Q >> admixture_k7.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.8.Q >> admixture_k8.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.9.Q >> admixture_k9.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.10.Q >> admixture_k10.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.11.Q >> admixture_k11.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.12.Q >> admixture_k12.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.13.Q >> admixture_k13.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.14.Q >> admixture_k14.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.15.Q >> admixture_k15.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.16.Q >> admixture_k16.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.17.Q >> admixture_k17.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.18.Q >> admixture_k18.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.19.Q >> admixture_k19.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.20.Q >> admixture_k20.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.21.Q >> admixture_k21.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.22.Q >> admixture_k22.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.23.Q >> admixture_k23.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.24.Q >> admixture_k24.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.25.Q >> admixture_k25.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.26.Q >> admixture_k26.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.27.Q >> admixture_k27.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.28.Q >> admixture_k28.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.29.Q >> admixture_k29.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.30.Q >> admixture_k30.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.31.Q >> admixture_k31.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.32.Q >> admixture_k32.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.33.Q >> admixture_k33.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.34.Q >> admixture_k34.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture15/cycas.maffiltered.4dtv.snp.35.Q >> admixture_k35.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.1.Q >> admixture_k1.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.2.Q >> admixture_k2.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.3.Q >> admixture_k3.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.4.Q >> admixture_k4.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.5.Q >> admixture_k5.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.6.Q >> admixture_k6.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.7.Q >> admixture_k7.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.8.Q >> admixture_k8.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.9.Q >> admixture_k9.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.10.Q >> admixture_k10.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.11.Q >> admixture_k11.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.12.Q >> admixture_k12.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.13.Q >> admixture_k13.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.14.Q >> admixture_k14.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.15.Q >> admixture_k15.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.16.Q >> admixture_k16.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.17.Q >> admixture_k17.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.18.Q >> admixture_k18.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.19.Q >> admixture_k19.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.20.Q >> admixture_k20.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.21.Q >> admixture_k21.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.22.Q >> admixture_k22.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.23.Q >> admixture_k23.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.24.Q >> admixture_k24.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.25.Q >> admixture_k25.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.26.Q >> admixture_k26.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.27.Q >> admixture_k27.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.28.Q >> admixture_k28.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.29.Q >> admixture_k29.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.30.Q >> admixture_k30.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.31.Q >> admixture_k31.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.32.Q >> admixture_k32.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.33.Q >> admixture_k33.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.34.Q >> admixture_k34.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture16/cycas.maffiltered.4dtv.snp.35.Q >> admixture_k35.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.1.Q >> admixture_k1.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.2.Q >> admixture_k2.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.3.Q >> admixture_k3.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.4.Q >> admixture_k4.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.5.Q >> admixture_k5.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.6.Q >> admixture_k6.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.7.Q >> admixture_k7.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.8.Q >> admixture_k8.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.9.Q >> admixture_k9.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.10.Q >> admixture_k10.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.11.Q >> admixture_k11.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.12.Q >> admixture_k12.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.13.Q >> admixture_k13.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.14.Q >> admixture_k14.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.15.Q >> admixture_k15.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.16.Q >> admixture_k16.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.17.Q >> admixture_k17.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.18.Q >> admixture_k18.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.19.Q >> admixture_k19.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.20.Q >> admixture_k20.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.21.Q >> admixture_k21.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.22.Q >> admixture_k22.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.23.Q >> admixture_k23.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.24.Q >> admixture_k24.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.25.Q >> admixture_k25.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.26.Q >> admixture_k26.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.27.Q >> admixture_k27.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.28.Q >> admixture_k28.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.29.Q >> admixture_k29.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.30.Q >> admixture_k30.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.31.Q >> admixture_k31.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.32.Q >> admixture_k32.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.33.Q >> admixture_k33.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.34.Q >> admixture_k34.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture17/cycas.maffiltered.4dtv.snp.35.Q >> admixture_k35.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.1.Q >> admixture_k1.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.2.Q >> admixture_k2.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.3.Q >> admixture_k3.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.4.Q >> admixture_k4.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.5.Q >> admixture_k5.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.6.Q >> admixture_k6.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.7.Q >> admixture_k7.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.8.Q >> admixture_k8.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.9.Q >> admixture_k9.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.10.Q >> admixture_k10.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.11.Q >> admixture_k11.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.12.Q >> admixture_k12.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.13.Q >> admixture_k13.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.14.Q >> admixture_k14.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.15.Q >> admixture_k15.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.16.Q >> admixture_k16.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.17.Q >> admixture_k17.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.18.Q >> admixture_k18.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.19.Q >> admixture_k19.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.20.Q >> admixture_k20.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.21.Q >> admixture_k21.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.22.Q >> admixture_k22.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.23.Q >> admixture_k23.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.24.Q >> admixture_k24.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.25.Q >> admixture_k25.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.26.Q >> admixture_k26.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.27.Q >> admixture_k27.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.28.Q >> admixture_k28.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.29.Q >> admixture_k29.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.30.Q >> admixture_k30.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.31.Q >> admixture_k31.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.32.Q >> admixture_k32.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.33.Q >> admixture_k33.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.34.Q >> admixture_k34.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture18/cycas.maffiltered.4dtv.snp.35.Q >> admixture_k35.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.1.Q >> admixture_k1.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.2.Q >> admixture_k2.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.3.Q >> admixture_k3.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.4.Q >> admixture_k4.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.5.Q >> admixture_k5.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.6.Q >> admixture_k6.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.7.Q >> admixture_k7.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.8.Q >> admixture_k8.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.9.Q >> admixture_k9.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.10.Q >> admixture_k10.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.11.Q >> admixture_k11.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.12.Q >> admixture_k12.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.13.Q >> admixture_k13.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.14.Q >> admixture_k14.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.15.Q >> admixture_k15.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.16.Q >> admixture_k16.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.17.Q >> admixture_k17.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.18.Q >> admixture_k18.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.19.Q >> admixture_k19.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.20.Q >> admixture_k20.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.21.Q >> admixture_k21.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.22.Q >> admixture_k22.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.23.Q >> admixture_k23.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.24.Q >> admixture_k24.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.25.Q >> admixture_k25.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.26.Q >> admixture_k26.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.27.Q >> admixture_k27.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.28.Q >> admixture_k28.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.29.Q >> admixture_k29.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.30.Q >> admixture_k30.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.31.Q >> admixture_k31.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.32.Q >> admixture_k32.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.33.Q >> admixture_k33.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.34.Q >> admixture_k34.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture19/cycas.maffiltered.4dtv.snp.35.Q >> admixture_k35.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.1.Q >> admixture_k1.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.2.Q >> admixture_k2.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.3.Q >> admixture_k3.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.4.Q >> admixture_k4.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.5.Q >> admixture_k5.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.6.Q >> admixture_k6.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.7.Q >> admixture_k7.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.8.Q >> admixture_k8.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.9.Q >> admixture_k9.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.10.Q >> admixture_k10.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.11.Q >> admixture_k11.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.12.Q >> admixture_k12.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.13.Q >> admixture_k13.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.14.Q >> admixture_k14.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.15.Q >> admixture_k15.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.16.Q >> admixture_k16.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.17.Q >> admixture_k17.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.18.Q >> admixture_k18.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.19.Q >> admixture_k19.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.20.Q >> admixture_k20.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.21.Q >> admixture_k21.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.22.Q >> admixture_k22.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.23.Q >> admixture_k23.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.24.Q >> admixture_k24.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.25.Q >> admixture_k25.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.26.Q >> admixture_k26.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.27.Q >> admixture_k27.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.28.Q >> admixture_k28.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.29.Q >> admixture_k29.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.30.Q >> admixture_k30.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.31.Q >> admixture_k31.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.32.Q >> admixture_k32.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.33.Q >> admixture_k33.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.34.Q >> admixture_k34.indfile
awk '{printf NR"\t"NR"\t""(0)""\t"4"\t"":""\t";for(i=1;i<=NF;i++){printf $i"\t"};{printf "\n"}}' admixture20/cycas.maffiltered.4dtv.snp.35.Q >> admixture_k35.indfile
