sed -i 's/SAMPLE_OLD/028/g' sample.list
sed -i 's/SAMPLE_OLD/069/g' sample.list
sed -i 's/SAMPLE_OLD/070/g' sample.list
sed -i 's/SAMPLE_OLD/1153/g' sample.list
sed -i 's/SAMPLE_OLD/5220/g' sample.list
sed -i 's/SAMPLE_OLD/5221/g' sample.list
sed -i 's/SAMPLE_OLD/5227/g' sample.list
sed -i 's/SAMPLE_OLD/5228/g' sample.list
sed -i 's/SAMPLE_OLD/5229/g' sample.list
sed -i 's/SAMPLE_OLD/776/g' sample.list
sed -i 's/SAMPLE_OLD/779/g' sample.list
sed -i 's/SAMPLE_OLD/JGY-02/g' sample.list
sed -i 's/SAMPLE_OLD/JGY-04/g' sample.list
sed -i 's/SAMPLE_OLD/JZS1/g' sample.list
sed -i 's/SAMPLE_OLD/JZS3/g' sample.list
sed -i 's/SAMPLE_OLD/JZS4/g' sample.list
sed -i 's/SAMPLE_OLD/LL01/g' sample.list
sed -i 's/SAMPLE_OLD/NJD010/g' sample.list
sed -i 's/SAMPLE_OLD/PZH1/g' sample.list
sed -i 's/SAMPLE_OLD/PZH2/g' sample.list
sed -i 's/SAMPLE_OLD/PZH3/g' sample.list
sed -i 's/SAMPLE_OLD/SAMPLE_NEW/g' sample.list
sed -i 's/SAMPLE_OLD/SAMPLE_NEW/g' sample.list
sed -i 's/SAMPLE_OLD/SAMPLE_NEW/g' sample.list
sed -i 's/SAMPLE_OLD/SAMPLE_NEW/g' sample.list
sed -i 's/SAMPLE_OLD/SAMPLE_NEW/g' sample.list
sed -i 's/SAMPLE_OLD/SAMPLE_NEW/g' sample.list
sed -i 's/SAMPLE_OLD/Y1/g' sample.list
sed -i 's/SAMPLE_OLD/Y6/g' sample.list
sed -i 's/SAMPLE_OLD/Y8/g' sample.list
sed -i 's/SAMPLE_OLD/Y9/g' sample.list
sed -i 's/SAMPLE_OLD/kz1/g' sample.list
sed -i 's/SAMPLE_OLD/kz2/g' sample.list
sed -i 's/SAMPLE_OLD/kz3/g' sample.list
sed -i 's/SAMPLE_OLD/xh1/g' sample.list
sed -i 's/SAMPLE_OLD/xh2/g' sample.list
sed -i 's/SAMPLE_OLD/xh4/g' sample.list
