#!/usr/bin/env Rscript
# =====================================================================
# p4_filter_pop.R - Single population private SNP filtering (called by script generated by p3, qsub available)
#
# Each task only reads 2 small tables: this group table + the total group table
#   others_alt = TOT_ALT - ALT_CT of this group (ALT copy number of all other groups)
#   Memory = O(number of bits), physical parallelism safe
#
# Usage: Rscript p4_filter_pop.R <pop.tsv> <total.tsv> <popfile> <outdir> <pop> [MAC] [MIN_GENO] [OTHERS_AF_MAX]
# Output: private_out/private.<pop>.txt Full table CHROM POS ID REF ALT
#       private_out/private.<pop>.extract CHROM POS two columns (for plink --extract)
#       private_out/<pop>.stats.tsv statistics (number of samples/number of candidates/number of private)
# =====================================================================
args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 5) {
  stop("Usage: Rscript p4_filter_pop.R <pop.tsv> <total.tsv> <popfile> <outdir> <pop> [MAC] [MIN_GENO] [OTHERS_AF_MAX]")
}
P_TSV  <- args[1]; T_TSV <- args[2]; POPFILE <- args[3]
OUTDIR <- args[4]; POP   <- args[5]
MAC    <- if (length(args) >= 6) as.numeric(args[6]) else 2
MIN_GENO <- if (length(args) >= 7) as.numeric(args[7]) else 0.8
OTHERS_AF_MAX <- if (length(args) >= 8) as.numeric(args[8]) else 0

p  <- read.table(P_TSV, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
t  <- read.table(T_TSV, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
pf <- read.table(POPFILE, header = FALSE, sep = "\t", stringsAsFactors = FALSE)
if (ncol(pf) < 2) stop("popfile requires at least two columns: sample ID<TAB>population")
n_g <- as.integer(table(pf[[2]])[POP])
if (is.na(n_g) || n_g < 1) stop(sprintf("No group [%s] in popfile", POP))

m <- match(p$ID, t$ID)
if (anyNA(m)) stop("The site IDs of pop.tsv and total.tsv are not exactly the same")
others_alt <- t$TOT_ALT[m] - p$ALT_CT
others_obs <- t$TOT_OBS[m] - p$OBS_CT

# Compliance within small groups (MAC + typing rate)
cand <- p$ALT_CT >= MAC & p$OBS_CT >= 2 * n_g * MIN_GENO
# Rest of the population ALT frequency <= upper limit (0 = strictly private)
if (OTHERS_AF_MAX <= 0) {
  priv <- cand & others_alt == 0
} else {
  o_af <- ifelse(others_obs > 0, others_alt / others_obs, 0)
  priv <- cand & o_af <= OTHERS_AF_MAX
}
sel <- p[priv, , drop = FALSE]

safe <- gsub("[^A-Za-z0-9_.-]", "_", POP)
dir.create(OUTDIR, showWarnings = FALSE, recursive = TRUE)
write.table(sel, file.path(OUTDIR, sprintf("private.%s.txt", safe)),
            sep = "\t", row.names = FALSE, quote = FALSE)
write.table(sel[, c("CHROM", "POS")],
            file.path(OUTDIR, sprintf("private.%s.extract", safe)),
            sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
write.table(data.frame(pop = POP, n_ind = n_g,
                       n_candidate = sum(cand), n_private = nrow(sel)),
            file.path(OUTDIR, sprintf("%s.stats.tsv", safe)),
            sep = "\t", row.names = FALSE, quote = FALSE)
cat(sprintf("[%s] Candidate %d, private SNP %d\n", POP, sum(cand), nrow(sel)))
